project:
  type: website


website:
  title: "simple_quarto_website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.ipynb
        text: About
      - href: slides/slide.ipynb
        text: slide
      
      

  
          

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

bibliography: reference.bib



